var constants = {};

// commands
constants.MSG_RETRY_GENERATE = "RETRY_GENERATE";

// server status updates
constants.MSG_SERVER_ONLINE = "SERVER_ONLINE";
constants.MSG_JOB_STARTED = "JOB_STARTED";
constants.MSG_JOB_FINISHED = "JOB_FINISHED";
constants.MSG_SERVER_BUSY = "SERVER_BUSY";

// supporting service updates
constants.MSG_DOWNLOAD_SERVER_ERROR = "DOWNLOAD_SERVER_ERROR";
constants.MSG_GENERATOR_RESTART = "GENERATOR_RESTART";
constants.MSG_GENERATOR_FAILURE_THRESHOLD = "GENERATOR_FAILURE_THRESHOLD";

// generate request updates
constants.MSG_GENERATE_PROGRESS = "GENERATE_PROGRESS";
constants.MSG_GENERATE_SUCCESS = "GENERATE_SUCCESS";
constants.MSG_GENERATE_FAILED = "GENERATE_FAILED";
constants.MSG_GENERATE_CANCELLED = "GENERATE_CANCELLED";
constants.MSG_CANCEL_FAILED = "CANCEL_FAILED";
constants.MSG_INVALID_CANCEL_REQ = "INVALID_CANCEL_REQ";
constants.MSG_CANCEL_IGNORED = "CANCEL_IGNORED";

module.exports = constants;