var constants = {};

constants.MSG_SERVER_ONLINE = "SERVER_ONLINE";
constants.MSG_RETRY_GENERATE = "RETRY_GENERATE";
constants.MSG_DOWNLOAD_SERVER_ERROR = "DOWNLOAD_SERVER_ERROR";
constants.MSG_CANCEL_FAILED = "CANCEL_FAILED";
constants.MSG_GENERATOR_RESTART = "GENERATOR_RESTART";
constants.MSG_GENERATOR_FAILURE_THRESHOLD = "GENERATOR_FAILURE_THRESHOLD";

module.exports = constants;